import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request'
import { PossibleTypeExtensionsRule } from 'graphql'
import BlogCard from '../components/BlogCard'

const graphcms = new GraphQLClient(
  "https://api-us-west-2.hygraph.com/v2/clah9l8za0jvd01t2hu7i45pj/master"
)

const QUERY = gql`
{
posts{
    title,
    datePublished,
    slug
    content{
      html
    }
    author {
      name
      avatar{
        url
      }
    }
    coverPhoto{
      url
    }
  }
}
`
//Fetch request from API
export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY)
  return {
    props: {
      posts,
    },
    revalidate: 10,
  }
}



export default function Home({ posts }) {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            key={post.id}
            datePublished={post.datePublished}
            slug={post.slug}
          />
        ))}
      </main>


    </div>
  )
}
